export enum ErrorCode {
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_REQUEST = 'INVALID_REQUEST',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
}
